from __future__ import annotations

from pathlib import Path

import pytest

from oeis_validator.parser import parse_entry
from oeis_validator.rules import validate

DATA_DIR = Path(__file__).parent.parent / "data"
DATA_FILES = sorted(DATA_DIR.glob("A*.txt"))

# Known warning counts per file — snapshot for regression detection.
# Generated by running the validator against each style-sheet-verified sequence.
EXPECTED_WARNING_COUNTS: dict[str, int] = {
    "A000005": 24,
    "A000010": 12,
    "A000040": 28,
    "A000041": 50,
    "A000045": 49,
    "A000108": 30,
    "A000203": 16,
    "A000217": 16,
    "A000290": 4,
    "A001222": 14,
}

# Warning message prefixes that are verified as valid per OEIS style sheet.
# Each entry maps a warning-field prefix to the style-sheet rule it enforces.
STYLE_SHEET_RULES: dict[str, str] = {
    "%o": "Language label required: 'give the name of the programming language in parentheses at the beginning, like (PARI) or (Perl)' (style sheet §Programs)",
    "%D": "URLs in %D: References are for 'material not found online' (style sheet §References); URLs belong in %H (Links)",
    "%F": "a_n/a[n] notation: use a(n) notation (style sheet §Name, §Spelling and notation)",
    "%H": "b-file placement: 'The b-file link(s) is placed at the beginning' of %H (style sheet §Links)",
    "%Y": "Duplicate cross-refs: 'comma-separated list of sequence numbers without repetition' (style sheet §Cross-references)",
}

# Fields for which the style sheet explicitly allows or expects warnings.
# %o language-label warnings are expected on every real OEIS sequence
# that has program lines; there are no false positives here.
KNOWN_WARNING_FIELDS = frozenset(STYLE_SHEET_RULES)


def entry_from_file(path: Path):
    text = path.read_text(encoding="utf-8")
    start = text.find("%I")
    assert start != -1, f"No %I marker found in {path}"
    return parse_entry(text[start:])


def _warnings_by_field(issues) -> dict[str, list[str]]:
    by_field: dict[str, list[str]] = {}
    for i in issues:
        if i.level == "WARNING":
            by_field.setdefault(i.field, []).append(i.message)
    return by_field


@pytest.mark.parametrize("path", DATA_FILES, ids=lambda p: p.stem)
def test_data_file_zero_errors(path: Path) -> None:
    entry = entry_from_file(path)
    issues = list(validate(entry))
    errors = [i for i in issues if i.level == "ERROR"]
    assert len(errors) == 0, (
        f"{path.stem}: {len(errors)} error(s): "
        + "; ".join(f"{i.field}: {i.message}" for i in errors)
    )


@pytest.mark.parametrize("path", DATA_FILES, ids=lambda p: p.stem)
def test_data_file_warning_count_snapshot(path: Path) -> None:
    entry = entry_from_file(path)
    issues = list(validate(entry))
    warns = [i for i in issues if i.level == "WARNING"]
    expected = EXPECTED_WARNING_COUNTS.get(path.stem)
    if expected is not None:
        assert len(warns) == expected, (
            f"{path.stem}: expected {expected} warnings, got {len(warns)}. "
            "If the validator intentionally changed, update EXPECTED_WARNING_COUNTS."
        )


@pytest.mark.parametrize("path", DATA_FILES, ids=lambda p: p.stem)
def test_data_file_style_sheet_valid(path: Path) -> None:
    entry = entry_from_file(path)
    issues = list(validate(entry))
    by_field = _warnings_by_field(issues)
    for field in by_field:
        assert field in KNOWN_WARNING_FIELDS, (
            f"{path.stem}: {field} warnings are not recognized by the style sheet. "
            f"Message: {by_field[field][0]}"
        )


def test_all_data_files_present() -> None:
    assert len(DATA_FILES) >= 10, f"Expected >=10 data files, found {len(DATA_FILES)}"
